[package]
name = "thegamerbay/super-coin-world"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
TestEZ = "roblox/testez@0.4.1"
Trove = "sleitnick/trove@1.3.0"
TypedRemote = "sleitnick/typed-remote@0.3.0"
RaycastHelper = "egomoose/raycast-helper@3.0.0"
CharacterSounds = "egomoose/character-sounds@0.2.1"
CharacterAnimate = "egomoose/character-animate@0.0.3"

[server-dependencies]
PlayerModule = "upliftgames/playermodule@700.0.7000935"
